/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_tobeing_threadtest_jniThread_JniThread */

#ifndef _Included_cn_tobeing_threadtest_jniThread_JniThread
#define _Included_cn_tobeing_threadtest_jniThread_JniThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_tobeing_threadtest_jniThread_JniThread
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_tobeing_threadtest_jniThread_JniThread_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
